export enum Colors {
  darkGrey = "#333",
  lightGrey = "#a4a4a4",
  orange = "#ff9a0a",
}
export enum ButtonTypes {
  number = "number",
  operator = "operator",
  memoryAdd = "m+",
  memoryClear = "mc",
  memoryRead = "mr",
  memorySubstract = "m-",
  changeSign = "changeSign",
  clearAll = "clearAll",
  equal = "equal",
  percentage = "percentage",
}
export enum Values {
  emptyString = "",
  one = "1",
  two = "2",
  three = "3",
  four = "4",
  five = "5",
  six = "6",
  seven = "7",
  eight = "8",
  nine = "9",
  point = ".",
  zero = "0",
  equal = "=",
  plus = "+",
  minus = "-",
  division = "/",
  mult = "*",
}
export enum Symbols {
  clearAll = "AC",
  changeSign = "+/-",
  percent = "%",
  memoryAdd = "m+",
  memoryClear = "mc",
  memorySubstract = "m-",
  memoryRead = "mr",
  one = "1",
  two = "2",
  three = "3",
  four = "4",
  five = "5",
  six = "6",
  seven = "7",
  eight = "8",
  nine = "9",
  comma = ",",
  zero = "0",
  equal = "=",
  plus = "+",
  minus = "-",
  division = "÷",
  mult = "×",
}
